### ISSUE TITLE
Not working m3 Sonoma 14.4

### ISSUE THREAD

**Issue by divineslight** [DKoenig82/simplestatspeed#2]
When I run app I see briefly "SimpleStatSpee" in the status bar, then it disappears and nothing happens.

The running app icon is in dock but it does nothing, if I quit and run again same happens.

**Comment by DKoenig82** [comment]
Maybe this helps:

You can open the app with a trick. Try to open the app again.
Then go to Settings under macOS, then Privacy & Security and finally open the SimpleStatSpeed app anyway!

**Comment by divineslight** [comment]
Mm, maybe I didn't explain it properly.

I did that already, it is running, it's in the Dock, but not displaying stats.

And... I had another app in the status bar, "QuickShade", quitting that made it work fine. That's weird..

It's running fine now. Both are working fine together.

Thank you, maybe this is not related to this app. So gonna close this now.
